### PR TITLE
Added poster template

### PR DESCRIPTION
**Pull request by ejeschke**
This adds a LaTeX poster template.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim,

Use the `Makefile` to build.  You may need a few latex packages, including `xelatex`.  I could find everything in the Ubuntu linux repo; RedHat should have all these too.

I just filled in a sample abstract, intro and conclusion.  Edit freely!

ADASS recommends to have a small picture of yourself in the upper right corner so that people can find you to talk about the poster.  I don't think it is a requirement though, feel free to replace it or get rid of it.  Posters are up the entire conference, IIRC.

I just picked 4 plugins from `stginga`; feel free to pick different ones, but whichever ones you pick it would be good if they represent ones that will be used for data analysis and quality assurance for HST and JWST.  I'm assuming you can write about each one: a brief description of what they are for and how they work.  I'll work on the latter section outlining how to write a plugin.  We'll go over the whole thing in a few iterations.

**Comment by ejeschke** [comment]
The plugin screenshots are all just stand-ins.  Replace them with ones showing your plugins in action.

**Comment by pllim** [comment]
Thanks, @ejeschke ! I'll merge this now so I can start working on it.

**Comment by ejeschke** [comment]
Let me know if you have trouble building it.  To get references correctly, you have to do something like:
```bash
$ xelatex poster.tex
$ xelatex poster.tex
$ bibtex poster
$ xelatex poster.tex
```

**Comment by ejeschke** [comment]
It's currently set at B0 size, but we could go to A0 if we need more room.

**Pull request merged**
