### PR TITLE
Add section on Writing a Ginga Plugin

### PR DESCRIPTION
**Pull request by ejeschke**
This adds the section on writing a ginga plugin.

### CODE REVIEW

**Comment by ejeschke** [comment]
@pllim, this adds just enough text to fill the poster to B0 size.  Suggest we merge and go into an edit cycle over the whole poster.

**Comment by pllim** [comment]
Ok I'll merge and review when I'm back from vacation. Thanks!

**Comment by pllim** [comment]
@ejeschke , do you know why this is in the `poster.log`?

```
! You can't use `macro parameter character #' in horizontal mode.
l.316 developers.html#
                      writing-plugins-for-the-reference-viewer).
Sorry, but I'm not programmed to handle this case;
I'll just pretend that you didn't ask for it.
If you're in the wrong mode, you might be able to
return to the right one by typing `I}' or `I$' or `I\par'.
```

**Comment by ejeschke** [comment]
"#" has special meaning for TeX.  So I think we probably need to escape it, maybe with a leading backslash.

**Pull request merged**
