### PR TITLE
Added paper per #9

### PR DESCRIPTION
**Pull request by ejeschke**
This adds the paper for the conference.  It's basically a copy of the text and images from poster.  We can edit it significantly, but it needs to clock in at 4 pages using the specified style unless they have changed the rules for posters this year.

### CODE REVIEW

**Comment by ejeschke** [comment]
Paper deadline is Nov 9

**Comment by pllim** [comment]
I'll merge first and edit later as separate PR. Thanks!

**Comment by pllim** [comment]
@ejeschke , how do I build the paper?

**Comment by ejeschke** [comment]
@pllim, type `make` a few times, to build up all the cross-references, etc.  There should be a `paper.pdf` left in the directory after building.

**Comment by ejeschke** [comment]
BTW, we need to change the name to comply with the naming scheme for the poster numbering scheme used by ADASS.  Did you get a number and letter for the poster? (Usually the letter is "P").

**Comment by pllim** [comment]
You mean the filename? Or specific variable name in the latex code?

**Comment by ejeschke** [comment]
The filename and the name of all the figures and the name of the bibliography file.  I think the reason is that they put everything into one big directory to build the proceedings!

**Comment by pllim** [comment]
> Did you get a number and letter for the poster? 

Not that I can find. How do I find it?

**Comment by pllim** [comment]
@ejeschke , is this the number (**P11.3**)? http://adass2018.umd.edu/abstracts/P11.3.html

**Pull request merged**
